# Node.js 이미지를 베이스로 사용
FROM node:22-alpine

# 작업 디렉토리 설정
WORKDIR /app

# 패키지 파일들 복사 및 의존성 설치
COPY package.json package-lock.json .env.localhost ./
RUN npm install --production

# 전체 소스 코드 복사
COPY . .

# 개발 환경 설정
ENV NODE_ENV=localhost

# Prisma 클라이언트 생성 (Prisma Schema에 따라 자동으로 생성)
RUN npx prisma generate --schema=./prisma/schema/

# 애플리케이션 빌드 (NestJS 빌드 스크립트에 따라 조정)
RUN npm run build

# 애플리케이션이 사용하는 포트 노출 (예: 1323)
EXPOSE 1323

# 애플리케이션 실행
CMD ["node", "dist/main.js"]