import { DomainPersonalAnalysis } from '../../domain/aggregates/personal-analysis.entity';
import { PersonalAnalysis } from '../../../../generated/prisma/client';
import { PairCount } from '../../domain/vos/pair-count.vo';

export class InfraPersonalAnalysisMapper {
  static toEntity(raw: PersonalAnalysis): DomainPersonalAnalysis {
    return new DomainPersonalAnalysis(
      raw.id,
      raw.sum,
      raw.cnt0s,
      raw.cnt10s,
      raw.cnt20s,
      raw.cnt30s,
      raw.cnt40s,
      raw.sumLastDigits,
      JSON.parse(raw.lastDigit0),
      JSON.parse(raw.lastDigit1),
      JSON.parse(raw.lastDigit2),
      JSON.parse(raw.lastDigit3),
      JSON.parse(raw.lastDigit4),
      JSON.parse(raw.lastDigit5),
      JSON.parse(raw.lastDigit6),
      JSON.parse(raw.lastDigit7),
      JSON.parse(raw.lastDigit8),
      JSON.parse(raw.lastDigit9),
      raw.even,
      raw.odd,
      raw.hot,
      raw.warm,
      raw.cold,
      raw.low,
      raw.high,
      raw.ac,
      JSON.parse(raw.consecutive),
      JSON.parse(raw.pair) as PairCount[],
      raw.prime,
      raw.composite,
      raw.mul3,
      raw.win1,
      raw.win2,
      raw.win3,
      raw.win4,
      raw.win5,
    );
  }

  static toPersistence(entity: DomainPersonalAnalysis): PersonalAnalysis {
    return {
      id: entity.id,
      sum: entity.sum,
      cnt0s: entity.cnt0s,
      cnt10s: entity.cnt10s,
      cnt20s: entity.cnt20s,
      cnt30s: entity.cnt30s,
      cnt40s: entity.cnt40s,
      sumLastDigits: entity.sumLastDigits,
      lastDigit0: entity.lastDigit0,
      lastDigit1: entity.lastDigit1,
      lastDigit2: entity.lastDigit2,
      lastDigit3: entity.lastDigit3,
      lastDigit4: entity.lastDigit4,
      lastDigit5: entity.lastDigit5,
      lastDigit6: entity.lastDigit6,
      lastDigit7: entity.lastDigit7,
      lastDigit8: entity.lastDigit8,
      lastDigit9: entity.lastDigit9,
      even: entity.even,
      odd: entity.odd,
      hot: entity.hot,
      warm: entity.warm,
      cold: entity.cold,
      low: entity.low,
      high: entity.high,
      ac: entity.ac,
      consecutive: JSON.stringify(entity.consecutive),
      pair: JSON.stringify(entity.pair),
      prime: entity.prime,
      composite: entity.composite,
      mul3: entity.mul3,
      win1: entity.win1,
      win2: entity.win2,
      win3: entity.win3,
      win4: entity.win4,
      win5: entity.win5,
    };
  }
}
