name: Generate DB Diff

on:
  workflow_dispatch:

jobs:
  generate-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Run script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/hactto-api
            CONTAINER_ID=\$(docker ps -q -f "name=hactto-api-" | head -n 1)
            docker exec \$CONTAINER_ID npx prisma migrate diff --from-url "\$(grep DATABASE_URL .env | cut -d '=' -f 2-)" --to-schema ./prisma/schema --script > diff.sql
            cat diff.sql
